name: chat_cat_game
description: "A Flutter project integrating a game and a chatbot."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.22.0
  flame_forge2d: ^0.16.0+2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  uuid: ^4.2.1
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  playing_cards: 0.3.1+9
  
  # Local packages
  jump_rope_game:
    path: packages/jump_rope_game
  ski_master:
    path: packages/ski_master
  flutter_blackjack_pkg:
    path: packages/Flutter_Blackjack
  flutter_suika_game:
    path: packages/flutter_suika_game
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7  # 추가
  freezed: ^2.4.6  # 추가
  pedantic_mono: ^1.25.0  # 추가

flutter:
  uses-material-design: true
  assets:
    - assets/images/gray_cat.png
    - assets/images/gray_cat_open_mouth.png
    - assets/images/suika_game/
    - assets/images/food.png
    - assets/images/sleep.png
    - assets/images/play.png
    - assets/images/speech_bubble.png
    - assets/images/pixel_cat.png
    - assets/images/fish.png
    - assets/images/
    - assets/audio/
    - assets/tiles/
    
